version: '3.8'

services:
  # Flask SecureShare API
  flask-api:
    build: 
      context: ./Secure File Sharing and Collaboration App for Contractors
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=SecureShare2025!@#$%^&*()_+{}|:<>?[]\\;\'\",./ 
      - JWT_SECRET_KEY=JWT-SecureShare-2025-SuperSecret-Key
    volumes:
      - ./flask_uploads:/app/uploads
      - ./flask_database:/app/database
    networks:
      - remodely-network
    restart: unless-stopped

  # Next.js RemodelyAz Website
  nextjs-web:
    build:
      context: ./remodely-website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - FLASK_API_URL=http://flask-api:5000
      - MONGODB_URI=${MONGODB_URI}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      - flask-api
    networks:
      - remodely-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nextjs-web
      - flask-api
    networks:
      - remodely-network
    restart: unless-stopped

networks:
  remodely-network:
    driver: bridge

volumes:
  flask_uploads:
    driver: local
  flask_database:
    driver: local
