services:
  - type: web
    name: remodelyaz
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_REGISTRY
        value: https://registry.npmjs.org/
      - key: YARN_PRODUCTION
        value: false
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DISABLE_YARN
        value: true
